### ISSUE TITLE
Using oneOf, generator failing looking for ((channel["publish"])["message"])["name"] which is undefined or falsey

### ISSUE THREAD

**Issue by DavidBiesack** [asyncapi/nodejs-template#62]
#### Describe the bug
When a channel uses `oneOf` instead of a single message, the generator fails
with Error: Unable to call `the return value of (the return value of (channel["publish"])["message"])["name"]`, which is undefined or falsey

#### How to Reproduce

Copy the sample from https://www.asyncapi.com/docs/tutorials/streetlights but use oneOf
(as a precursor to publishing multiple events to that channel).

Source:

```yaml
asyncapi: '2.0.0'
info:
  title: Streetlights API
  version: '1.0.0'
  description: |
    The Smartylighting Streetlights API allows you
    to remotely manage the city lights.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
servers:
  mosquitto:
    url: mqtt://test.mosquitto.org
    protocol: mqtt
channels:
  light/measured:
    publish:
      summary: Inform about environmental lighting conditions for a particular streetlight.
      operationId: onLightMeasured
      message:
        oneOf:
          - name: LightMeasured
            payload:
              type: object
              properties:
                id:
                  type: integer
                  minimum: 0
                  description: Id of the streetlight.
                lumens:
                  type: integer
                  minimum: 0
                  description: Light intensity measured in lumens.
                sentAt:
                  type: string
                  format: date-time
                  description: Date and time when the message was sent.

```

run:

```bash
ag --output __sdk asyncapi.yaml @asyncapi/nodejs-template -p server=mosquitto

Something went wrong:
Template render error: (~/.nvm/versions/node/v12.21.0/lib/node_modules/@asyncapi/nodejs-template/template/src/api/routes/$$channel$$.js) [Line 13, Column 81]
  Error: Unable to call `the return value of (the return value of (channel["publish"])["message"])["name"]`, which is undefined or falsey
    at Object._prettifyError (~/dev/asyncapi/async-events-api-def/node_modules/nunjucks/src/lib.js:36:11)
    at ~/dev/asyncapi/async-events-api-def/node_modules/nunjucks/src/environment.js:563:19
    at Template.root [as rootRenderFunc] (eval at _compile (~/dev/asyncapi/async-events-api-def/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:60:3)
    at Template.render (~/dev/asyncapi/async-events-api-def/node_modules/nunjucks/src/environment.js:552:10)
    at Environment.renderString (~/dev/asyncapi/async-events-api-def/node_modules/nunjucks/src/environment.js:380:17)
    at ~/dev/asyncapi/async-events-api-def/node_modules/@asyncapi/generator/lib/renderer/nunjucks.js:32:14
    at new Promise (<anonymous>)
    at nunjucksExport.renderNunjucks (~/dev/asyncapi/async-events-api-def/node_modules/@asyncapi/generator/lib/renderer/nunjucks.js:31:10)
    at Generator.renderFile (~/dev/asyncapi/async-events-api-def/node_modules/@asyncapi/generator/lib/generator.js:688:12)
    at Generator.renderAndWriteToFile (~/dev/asyncapi/async-events-api-def/node_modules/@asyncapi/generator/lib/generator.js:602:27)
```

#### Expected behavior

iterator over all the messages in the `oneOf`
