### ISSUE TITLE
MQTT connection configuration support

### ISSUE THREAD

**Issue by TamimiGitHub** [asyncapi/nodejs-template#7]
This templates depends on [hermes-mqtt](https://github.com/fmvilas/hermes-mqtt) to connect to an mqtt server, which doesnt support extra configuration connection (as per this issue https://github.com/fmvilas/hermes-mqtt/issues/1). 

# Suggestion
Ideally, once extra configuration options are supported in the hermes-mqtt package, the common.yml will need to be configured in such a way it supports passing a config object when mqtt is specified as a protocol:

```
{%- if asyncapi.server(params.server).protocol() === "mqtt" %}
    mqtt:
      url: mqtt://{{ asyncapi.server(params.server).url() | replaceVariablesWithValues(asyncapi.server(params.server).variables()) | stripProtocol  }}
      topics: {{ asyncapi | channelNamesWithPublish | toMqttTopic | dump | safe }}
      qos:
      protocol: mqtt
      retain:
      subscribe: true
      config: {do something to port configuration options from .yml file}
```
And the MqttAdapter should already be able to handle this configuration parameter here
https://github.com/asyncapi/nodejs-template/blob/master/template/src/api/index.js#L16
