### ISSUE TITLE
Support referencing additional yaml files in asyncapi.yaml file

### ISSUE THREAD

**Issue by predhme** [asyncapi/nodejs-template#88]
#### Reason/Context

We have a number of services defined in multiple yaml files. As one can imagine, there can be commonality in message payload definitions. To reduce duplication we identified the commonality between files defined them in a `common.yaml` file. For a more concrete picture, consider the two following yaml files

```yaml
# asyncapi.yaml
asyncapi: 2.0.0
info:
  title: test
  version: 0.0.1
  description: test

servers:
  development:
    url: tcp://test.mosquitto.org:1883
    protocol: mqtt

channels:

  send:
    description: sends a message
    publish:
      operationId: sendMessage
      message:
        name: sendMessage
        payload: 
          $ref: './common.yaml#/schemas/message'
```

```yaml
# common.yaml
---
schemas:

  message:
    type: object
    properties:
      message:
        type: string
    required:
      - message
```

The generator seems to respect these references, however, the referenced files are not present in the generated source. As such, when validation occurs, the process fails because it cannot open the referenced file. 

This feature would be useful for larger projects that would like to reduce duplication. 

#### Description

Since the generator does not complain about referenced yaml files, it would be useful for the template to copy the referenced yamls into the generated project. I am unsure of how the template/generator work together to achieve the desired result. It would seem that a list of references could be kept and copied into the generated source.
